- repo: local
  hooks:
    - id: ansible-lint
      name: Ansible-lint
      description: This hook runs ansible-lint.
      entry: ansible-lint -c .ansible-lint --force-color
      language: python
      # do not pass files to ansible-lint, see:
      # https://github.com/ansible/ansible-lint/issues/611
      pass_filenames: false
      always_run: true