# Use this file for installing your roles when you run the install roles playbook.

#For ec roles
#- name: edmondscommerce.lxc
#  src: git@github.com:edmondscommerce/ansible-role-lxc.git
#  scm: git
#  version: master

#For none ec roles
#- src: geerlingguy.repo-remi
##- src: geerlingguy.git
